fix Gallery Component - wrong image order
Synapse-Cmf/synapse-cmf pull request #54
Opened 2017-03-27 00:34 UTC by Oliboy50

Fix #50

2017-03-27 07:57 UTC, cmoysan approved these changes

2017-03-29 07:09 UTC, lvrbacconnier approved these changes

2017-03-29 07:42 UTC, cmoysan approved these changes

2017-03-29 09:53 UTC, Nyxis requested changes

2017-03-29 09:53 UTC, Nyxis commented on src/Synapse/Cmf/Bundle/Controller/GalleryComponentController.php
> +            $mediaData[$mediaIndex] = $imageLoader->retrieve($mediaId);
Trop de requêtes ici, implémente plutôt un sort dans la collection.

2017-03-29 15:54 UTC, Oliboy50 commented on src/Synapse/Cmf/Bundle/Controller/GalleryComponentController.php
> +            $mediaData[$mediaIndex] = $imageLoader->retrieve($mediaId);
@Nyxis done

2017-04-03 09:49 UTC, Nyxis requested changes

2017-04-03 09:49 UTC, Nyxis commented on src/Synapse/Cmf/Framework/Media/Image/Entity/ImageCollection.php
> +    public function sortIdsAtTheTop(array $ids)
Tu n'as pas besoin de prendre les ids en paramètre, tu as déjà les objets dans la collection. Utilise la fonction `sort` qui fait une bonne partie du travail.

2017-04-03 19:21 UTC, Oliboy50 commented on src/Synapse/Cmf/Framework/Media/Image/Entity/ImageCollection.php
> +    public function sortIdsAtTheTop(array $ids)
le but est de faire passer certains éléments (définis par leur "id") de la collection en tête de cette collection

exemple : 
```php
$collection = new ImageCollection([
    (new Image())->setId(1),
    (new Image())->setId(2),
    (new Image())->setId(3),
    (new Image())->setId(42),
]);
// [ 1, 2, 3, 42 ]

$collection->sortIdsAtTheTop([2, 42]);
// [ 2, 42, 1, 3 ]
```

je n'vois pas comment faire autrement

2019-05-17 07:23 UTC, Oliboy50 commented
😘

2019-05-17 07:23 UTC, closed without merging